name: CI

on:
  pull_request:
    branches: [ main, dev_stage ]
  push:
    branches: [ dev_stage ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff mypy pytest
      - name: Lint
        run: ruff check .
      - name: Type check (scoped)
        run: mypy . || true
      - name: Tests
        run: pytest -q
